### ISSUE TITLE
UnboundLocalError: cannot access local variable 'redis' where it is not associated with a value

### ISSUE THREAD

**Issue by Youssefbenhammouda** [shobrook/gptlimiter#3]
When using the `ChatRateLimiterWithRedis`, I get this error:

> site-packages\openlimit\redis_rate_limiters.py", line 40, in _init_buckets
>     redis = await redis.asyncio.from_url(self._redis_url, encoding="utf-8", decode_responses=True)
>                   ^^^^^
> UnboundLocalError: cannot access local variable 'redis' where it is not associated with a value

My Python version is 3.11, I am using the last version of the library (openlimit==0.2.7).
After inspecting the code, I found out there's a problem In the code:
```
....
import redis
.....
    async def _init_buckets(self):
        if self._request_bucket and self._token_bucket:
            return

        redis = await redis.asyncio.from_url(self._redis_url, encoding="utf-8", decode_responses=True) # the line where the problem is.
        
        self._request_bucket = RedisBucket(
            self.request_limit,
            bucket_key=f"{self._bucket_key}_requests",
            redis=redis
        )
```
        
 Even if redis is not yet declared, Python considers it as a local variable so it ignores the global library and raises the error.
 You can fix this by setting `global redis` at the beginning of the function or renaming the variable.

**Comment by shobrook** [comment]
Should be fixed in `v0.3.0` of the package.
