### ISSUE TITLE
What is max_tokens in the token counting utilities, please?

### ISSUE THREAD

**Issue by jucor** [shobrook/gptlimiter#6]
Hi @shobrook 

Thanks for the tool!
Asking here a similar question as on https://github.com/blaze-Youssef/openai-ratelimiter/issues/2 , which uses the same code.

What does the argument `max_tokens` correspond to, please, in https://github.com/shobrook/openlimit/blob/master/openlimit/utilities/token_counters.py#L14 , please?

I am trying to understand it, but the way you count tokens seems different than in OpenAI's cookbook https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb (see section 6), which does not have such a starting count at `n*max_tokens`.

Thanks for any clarification!

**Comment by jucor** [comment]
Ah! Found max_tokens in the OpenAI API, as an optional parameter: https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens
Do I understand correctly that setting the baseline to `n*max_tokens` is here to preemptively count into the rate limit the maximum possible number of output tokens?

**Comment by jucor** [comment]
Ungh, now I see that OpenAI has a separate token counter in their batch-API script than in their tutorial Notebook: https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py#L339
The former does indeed take max_tokens into account. But is also less recent than their notebook, which has different token increments for roles' names. So I don't know which version of their token counter to believe 😅

Shouldn't a rate limiter, in any case, be updated after the actual completion is returned by the API, to account for the actual number of output tokens?

**Comment by shobrook** [comment]
> Do I understand correctly that setting the baseline to n*max_tokens is here to preemptively count into the rate limit the maximum possible number of output tokens?

Yes.

> Shouldn't a rate limiter, in any case, be updated after the actual completion is returned by the API, to account for the actual number of output tokens?

No. This implementation attempts to throttle requests _before_ they're made to OpenAI. To do this, we have to assume the worst case scenario for token consumption.
